version: "3"

services:

  app:
    image: meteosangue/meteosangue:latest
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis
    command: ./docker-startup.sh app
    env_file:
      - ./envs/meteosangue.env
      - ./envs/db.env

  cron:
    image: meteosangue/meteosangue:latest
    restart: always
    depends_on:
      - app
      - db
      - redis
    command: ./docker-startup.sh cron
    env_file:
      - ./envs/meteosangue.env
      - ./envs/db.env

  redis:
    image: redis:3-alpine

  db:
    image: postgres:11.5
    restart: unless-stopped
    env_file:
      - ./envs/db.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
