version: "3"

services:

  app:
    build: meteosangue/meteosangue
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./envs/meteosangue.env
      - ./envs/db.env

  redis:
    image: redis:3-alpine

  db:
    image: postgres:11.5
    restart: unless-stopped
    env_file:
      - ./envs/db.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
